# Generated by Django 5.1.4 on 2025-01-13 23:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_exercise_delete_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="weight",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="exercise",
            name="sets",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MaxValueValidator(100),
                    django.core.validators.MinValueValidator(1),
                ],
            ),
        ),
    ]
